### ISSUE TITLE
Initializing ClusterThenLabeller object

### ISSUE THREAD

**Issue by Efesencan** [gudgud96/semi-supervised-learning#1]
In the cluster-then-label.py file on line 200, you initialize the ClusterThenLabeller object with unlablledX and unlablledy parameters.
(model = ClusterThenLabeller(X_unlabelled, Y_unlabelled, xlabel, ylabel, filename). But shouldn't you provide both labeled and unlabeled version of the data for the initialization part instead of just providing only unlabeled data. Or the names of the parameters are misleading? Thanks in advance.

**Comment by Efesencan** [comment]
In addition to that, while selecting the labeledX and labeledY part in cluster_then_label method, are you assuming that the unlabeled data will be denoted as 0?

**Comment by gudgud96** [comment]
Hi @Efesencan,

Thank you for your question. Sorry that this repo is not being maintained for quite some time already. For the first question, I believe you are right, there should be some additional lines to concatenate the labelled and unlabelled ones together, that line might have been missed in this committed version.

For the second question, yes unlabelled data will have label 0 in the Y_data part, but you can check back the original [KEEL dataset](https://sci2s.ugr.es/keel/semisupervised.php) for reference.

Thanks again!

**Comment by Efesencan** [comment]
Hello @gudgud96 , thanks for your answer. My another comment would be when you make predictions (y_predict) after clustering and labeling, it might be better to remove the invalid predictions from your y_predict set and their corresponding instances from X_data during the fit the model process for evaluating test accuracy. Otherwise you are trying to fit the model which consists of invalid labels. Hence the model's performance could decrease.  

Have a nice day.
